//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quick_Med_Kit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commande
    {
        public int ID_Commande { get; set; }
        public int Code_Medicament { get; set; }
        public int ID_Utilisateur { get; set; }
        public Nullable<int> ID_Livreur { get; set; }
        public Nullable<System.DateTime> Date_Commande { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Prix { get; set; }
        public Nullable<decimal> total { get; set; }
    
        public virtual Medicament Medicament { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
        public virtual Livreur Livreur { get; set; }
    }
}
