//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quick_Med_Kit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicament
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medicament()
        {
            this.Commande = new HashSet<Commande>();
        }
    
        public int Code_Medicament { get; set; }
        public string Nom { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Date_Production { get; set; }
        public Nullable<System.DateTime> Date_expiration { get; set; }
        public string Droit_Usage { get; set; }
        public Nullable<decimal> Prix { get; set; }
        public string upload_images { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Commande> Commande { get; set; }
    }
}
